### ISSUE TITLE
Is this repository being used?

### ISSUE THREAD

**Issue by usanchez** [onnela-lab/Beiwe-Analysis#4]
My doubt is if this repository is being used or has been deprecated. For the Data Analysis pipeline process described in [Data Analysis Pipeline setup and update instructions](https://github.com/onnela-lab/beiwe-backend/wiki/Data-Analysis-Pipeline-setup-and-update-instructions), do we have to use this repo or has this code been merged to the `beiwe-backend` repo (I don't know if `production` or `pipeline` branch)?

I followed this process a long ago, but I think I had some difficulties using the code from this repo as it was not complete and I think that I had to use some code from the `beiwe-backend` repo. Sorry that I cannot be more specific, but I'll try to set it up again if you need it to improve the documentation.

Thank you very much!

**Comment by ianjamesbarnett** [comment]
While I no longer maintain this repository, this should still work so long as the format of Beiwe data hasn’t changed since I worked for JP. If data formats have changed then this indeed will be deprecated.

Ian

*edited to clear out some junk that got injected due to Ian's email client - Eli*

**Comment by biblicabeebli** [comment]
This repository is still in use, but as Ian said above its functionality is static.  If there is more major development to be done it would be by a data scientist associated with J.P. Onnela.  While I maintain the various Beiwe codebases and server architecture/administration I am not a data scientist and cannot continue or enhance development on this repo.

This repository is used by the Data Pipeline component of Beiwe, and there has been some development on it "recently".  However, because there was no development of the integration with the Data Pipeline automation system it currently only has coverage a few data streams that myself and a coworker were able to hack together.  Given the level of commitment on this repository vs the necessary work to maintain the existing raw data collection components of Beiwe (e.g. the Python 3 conversion, necessary because Python 2 dead and gone on Jan 1) this repo has seen zero development.

There may be development in the future to get the remaining existing data streams covered in the automated pipeline.

**Comment by usanchez** [comment]
So, If I want to get all the production data of a study I should still use this repo, right?

Thank you both for your answers.

**Comment by biblicabeebli** [comment]
Yeah, you will have to set up the pipeline.

FYI the pipeline servers pull in the most recent pipeline branch of this repo before executing.  If it is upgraded to include new data streams you will see them automatically.

By default the backend server will mot automatically run the pipeline code, you will have to go in and trigger a manual run on a per study basis.  The directions for setting up the pipeline should be unchanged as this code was already python 3.  Please let me know if it does not.
